# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import position_pb2 as proto_dot_position__pb2


class PositinServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PositionReq = channel.unary_unary(
        '/posXYZ.PositinService/PositionReq',
        request_serializer=proto_dot_position__pb2.Msg.SerializeToString,
        response_deserializer=proto_dot_position__pb2.Position.FromString,
        )
    self.PositionPub = channel.unary_unary(
        '/posXYZ.PositinService/PositionPub',
        request_serializer=proto_dot_position__pb2.Position.SerializeToString,
        response_deserializer=proto_dot_position__pb2.Msg.FromString,
        )


class PositinServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PositionReq(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PositionPub(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PositinServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PositionReq': grpc.unary_unary_rpc_method_handler(
          servicer.PositionReq,
          request_deserializer=proto_dot_position__pb2.Msg.FromString,
          response_serializer=proto_dot_position__pb2.Position.SerializeToString,
      ),
      'PositionPub': grpc.unary_unary_rpc_method_handler(
          servicer.PositionPub,
          request_deserializer=proto_dot_position__pb2.Position.FromString,
          response_serializer=proto_dot_position__pb2.Msg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'posXYZ.PositinService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
